// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3Xor1Wn6kyNwru0cGSoZdCZwzvKv69Y',
    appId: '1:958423443778:web:09238143188297b378c0db',
    messagingSenderId: '958423443778',
    projectId: 'job-board-322da',
    authDomain: 'job-board-322da.firebaseapp.com',
    databaseURL: 'https://job-board-322da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'job-board-322da.firebasestorage.app',
    measurementId: 'G-RMZEKE1NKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeSnyOAh4stoJ0MbT--revM5Mm6_lJ7_o',
    appId: '1:958423443778:android:830bd3e96203ed7778c0db',
    messagingSenderId: '958423443778',
    projectId: 'job-board-322da',
    databaseURL: 'https://job-board-322da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'job-board-322da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc0aPe_Yu60DddjMl4vQhJpZlKpGQZLlI',
    appId: '1:958423443778:ios:638288f86e3fec2e78c0db',
    messagingSenderId: '958423443778',
    projectId: 'job-board-322da',
    databaseURL: 'https://job-board-322da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'job-board-322da.firebasestorage.app',
    iosBundleId: 'com.example.jobBoardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc0aPe_Yu60DddjMl4vQhJpZlKpGQZLlI',
    appId: '1:958423443778:ios:638288f86e3fec2e78c0db',
    messagingSenderId: '958423443778',
    projectId: 'job-board-322da',
    databaseURL: 'https://job-board-322da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'job-board-322da.firebasestorage.app',
    iosBundleId: 'com.example.jobBoardFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD3Xor1Wn6kyNwru0cGSoZdCZwzvKv69Y',
    appId: '1:958423443778:web:4f4ff315f9a1911978c0db',
    messagingSenderId: '958423443778',
    projectId: 'job-board-322da',
    authDomain: 'job-board-322da.firebaseapp.com',
    databaseURL: 'https://job-board-322da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'job-board-322da.firebasestorage.app',
    measurementId: 'G-BCLYKMC7SQ',
  );
}
